/* Generated By:JavaCC: Do not edit this line. ETU_TVLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ETU_TVLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int PROGRAM = 8;
  /** RegularExpression Id. */
  int DECLARATION_SECTION = 9;
  /** RegularExpression Id. */
  int INITIALIZATION_SECTION = 10;
  /** RegularExpression Id. */
  int MAIN_SECTION = 11;
  /** RegularExpression Id. */
  int INPUT = 12;
  /** RegularExpression Id. */
  int OUTPUT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int UNKNOWN = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 20;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int MESSAGE = 25;
  /** RegularExpression Id. */
  int ID = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"--\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 3>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"PROGRAM\"",
    "\"DECLARATION SECTION\"",
    "\"INITIALIZATION SECTION\"",
    "\"MAIN SECTION\"",
    "\"INPUT\"",
    "\"OUTPUT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"UNKNOWN\"",
    "\"AND\"",
    "\"NOT\"",
    "\"OR\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "<MESSAGE>",
    "<ID>",
  };

}
